# Generated by Django 5.2 on 2025-05-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
